baseURL = "https://mccannlab.github.io/"
languageCode = "en-us"
title = "The McCann Lab"
theme = "xmin_kevcaz"
twitterUsername = "mccannlab"
github = "McCannLab"
googlefont = "Lato"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    projects = "/projects/:year/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Members"
    url = "/members/"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4
[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 5

[[menu.icon]]
    url = "https://github.com/McCannLab"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/mccannlab"
    name = "twitter"
    weight = 2

[params]
    description = "McCannLab website"
    footer = "&copy; McCannLab 2018"
