baseURL = "http://example.org/"
languageCode = "en-us"
title = "CFREF aquatics"
theme = "xmin_kevcaz"
twitterUsername = "mccannlab"
github = "AquaticGuelph"
googlefont = "Lato"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Members"
    url = "/members/"
    weight = 3
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Hugo website CFREF Aquatics"
    footer = "&copy; [Kevin Cazelles](http://kevincazelles.fr/) 2018"
